update for solution content and social media content
vac-soft/vac-soft.github.io pull request #9
Opened 2023-02-09 07:14 UTC by abdulfahadlee

2023-02-10 17:13 UTC, dkkaran1996 commented on assets/_templates/_header.php
> +                                                <li><a href="../../products.php#CRM" class="dropdown-item" type="button">Real Management</a></li>
Its Real Estate Management

2023-02-10 17:24 UTC, dkkaran1996 requested changes
1. Some links shows different # and product are different in header.php
2. price.php file marking to PRODUCTS.php

2023-02-10 17:26 UTC, dkkaran1996 requested changes

2023-02-10 17:26 UTC, dkkaran1996 commented on assets/_templates/_price.php
> +                                        <li><a href="../../PRODUCTS.php" class="dropdown-item" type="button">Call Center Dialer</a></li>
It should be products.php instead of PRODUCTS.php

2023-02-13 04:24 UTC, abdulfahadlee commented on assets/_templates/_header.php
> +                                                <li><a href="../../products.php#CRM" class="dropdown-item" type="button">Real Management</a></li>
product details need real estate managment content for webpage.

2023-02-13 11:31 UTC, closed without merging